#!/bin/bash
# // Lunatic
grenbo="\e[92;1m"
NC='\033[0m'
clear
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│$NC\033[42m          MENU MANAGER SYSTEM             $NC"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│  ${grenbo}1.${NC} \033[0;36mChange Banner${NC}"
echo -e "\033[1;93m│  ${grenbo}2.${NC} \033[0;36mChange Domain${NC}"
echo -e "\033[1;93m│  ${grenbo}3.${NC} \033[0;36mFix Cert Domain${NC}"
echo -e "\033[1;93m│  ${grenbo}4.${NC} \033[0;36mClear Chache / Sampah${NC}"
echo -e "\033[1;93m│  ${grenbo}5.${NC} \033[0;36mCreate Slowdns${NC}"
echo -e "\033[1;93m│  ${grenbo}6.${NC} \033[0;36mCheck Running Service${NC}"
echo -e "\033[1;93m│  ${grenbo}7.${NC} \033[0;36mSpeedTest${NC}"
echo -e "\033[1;93m│  ${grenbo}8.${NC} \033[0;36mBackup BOT${NC}"
echo -e "\033[1;93m│  ${grenbo}0.${NC} \033[0;36mComeBack Menu${NC}"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 8 or 0 ] : " menu
case $menu in
1) clear ;
    nano /etc/kyt.txt
    ;;
2) clear ;
    addhost
    ;;
3) clear ;
    fixcert
    ;;
4) clear ;
    clearcache
    ;;
5) clear ;
    sd
    ;;
6) clear ;
   run
   ;;
7) clear ;
  speedtest
  ;;
8) clear ;
  mbot-backup
  ;;
*)
    menu
    ;;
esac
