#!/bin/bash
# // Lunatic
grenbo="\e[92;1m"
NC='\033[0m'
clear
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│$NC\033[42m          MENU MANAGER TRIAL              $NC"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│  ${grenbo}1.${NC} \033[0;36mTRIALL SSH ACCOUNT${NC}"
echo -e "\033[1;93m│  ${grenbo}2.${NC} \033[0;36mTRIALL SS ACCOUNT${NC}"
echo -e "\033[1;93m│  ${grenbo}3.${NC} \033[0;36mTRIALL TROJAN ACCOUNT${NC}"
echo -e "\033[1;93m│  ${grenbo}4.${NC} \033[0;36mTRIALL VLESS ACCOUNT${NC}"
echo -e "\033[1;93m│  ${grenbo}5.${NC} \033[0;36mTRIALL VMESS ACCOUNT${NC}"
echo -e "\033[1;93m│  ${grenbo}0.${NC} \033[0;36mComeBack Menu${NC}"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 5 or 0 ] : " menu
case $menu in
1) clear ;
    trial
    ;;
2) clear ;
    trialss
    ;;
3) clear ;
    trialtr
    ;;
4) clear ;
    trialvless
    ;;
5) clear ;
    trialws
    ;;
*)
    menu
    ;;
esac
